/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v7.0
processor: MK60DN512xxx10
package_id: MK60DN512VLQ10
mcu_data: ksdk2_0
processor_version: 7.0.1
pin_labels:
- {pin_num: '78', pin_signal: PTA27/MII0_CRS/FB_A26, label: SENS, identifier: SENS}
- {pin_num: '58', pin_signal: PTA6/FTM0_CH3/TRACE_CLKOUT, label: D_SEG_C, identifier: D_SEG_C}
- {pin_num: '59', pin_signal: ADC0_SE10/PTA7/FTM0_CH4/TRACE_D3, label: D_C2, identifier: D_SEG_E;D_C2}
- {pin_num: '60', pin_signal: ADC0_SE11/PTA8/FTM1_CH0/FTM1_QD_PHA/TRACE_D2, label: D_SEG_D, identifier: D_SEG_A;D_SEG_D}
- {pin_num: '61', pin_signal: PTA9/FTM1_CH1/MII0_RXD3/FTM1_QD_PHB/TRACE_D1, label: D_C3, identifier: D_SEG_F;D_C3}
- {pin_num: '62', pin_signal: PTA10/FTM2_CH0/MII0_RXD2/FTM2_QD_PHA/TRACE_D0, label: D_SEG_DOT, identifier: D_SEG_B;D_SEG_DOT}
- {pin_num: '63', pin_signal: PTA11/FTM2_CH1/MII0_RXCLK/FTM2_QD_PHB, label: D_SEG_G, identifier: D_SEG_D;D_SEG_G}
- {pin_num: '52', pin_signal: TSI0_CH3/PTA2/UART0_TX/FTM0_CH7/JTAG_TDO/TRACE_SWO/EZP_DO, label: D_C1, identifier: D_SEG_DOT;D_C1}
- {pin_num: '53', pin_signal: TSI0_CH4/PTA3/UART0_RTS_b/FTM0_CH0/JTAG_TMS/SWD_DIO, label: D_C4, identifier: D_SEG_G;D_C4}
- {pin_num: '141', pin_signal: PTD12/SPI2_SCK/SDHC0_D4/FB_A20, label: D_SEG_B, identifier: D_C1;D_SEG_B}
- {pin_num: '142', pin_signal: PTD13/SPI2_SOUT/SDHC0_D5/FB_A21, label: D_SEG_F, identifier: D_C2;D_SEG_F}
- {pin_num: '144', pin_signal: PTD15/SPI2_PCS1/SDHC0_D7/FB_A23, label: D_SEG_A, identifier: D_C3;D_SEG_A}
- {pin_num: '143', pin_signal: PTD14/SPI2_SIN/SDHC0_D6/FB_A22, label: D_SEG_E, identifier: D_C4;D_SEG_E}
- {pin_num: '47', pin_signal: PTE26/ENET_1588_CLKIN/UART4_CTS_b/RTC_CLKOUT/USB_CLKIN, label: FUN_BTN, identifier: START_BTN;FUN_BTN}
- {pin_num: '29', pin_signal: PGA1_DP/ADC1_DP0/ADC0_DP3, label: SENSOR, identifier: SENSOR}
- {pin_num: '27', pin_signal: PGA0_DP/ADC0_DP0/ADC1_DP3, label: SENSOR, identifier: SENSOR}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '58', peripheral: GPIOA, signal: 'GPIO, 6', pin_signal: PTA6/FTM0_CH3/TRACE_CLKOUT, direction: OUTPUT}
  - {pin_num: '59', peripheral: GPIOA, signal: 'GPIO, 7', pin_signal: ADC0_SE10/PTA7/FTM0_CH4/TRACE_D3, identifier: D_C2, direction: OUTPUT}
  - {pin_num: '60', peripheral: GPIOA, signal: 'GPIO, 8', pin_signal: ADC0_SE11/PTA8/FTM1_CH0/FTM1_QD_PHA/TRACE_D2, identifier: D_SEG_D, direction: OUTPUT}
  - {pin_num: '61', peripheral: GPIOA, signal: 'GPIO, 9', pin_signal: PTA9/FTM1_CH1/MII0_RXD3/FTM1_QD_PHB/TRACE_D1, identifier: D_C3, direction: OUTPUT}
  - {pin_num: '62', peripheral: GPIOA, signal: 'GPIO, 10', pin_signal: PTA10/FTM2_CH0/MII0_RXD2/FTM2_QD_PHA/TRACE_D0, identifier: D_SEG_DOT, direction: OUTPUT}
  - {pin_num: '63', peripheral: GPIOA, signal: 'GPIO, 11', pin_signal: PTA11/FTM2_CH1/MII0_RXCLK/FTM2_QD_PHB, identifier: D_SEG_G, direction: OUTPUT}
  - {pin_num: '52', peripheral: GPIOA, signal: 'GPIO, 2', pin_signal: TSI0_CH3/PTA2/UART0_TX/FTM0_CH7/JTAG_TDO/TRACE_SWO/EZP_DO, identifier: D_C1, direction: OUTPUT}
  - {pin_num: '53', peripheral: GPIOA, signal: 'GPIO, 3', pin_signal: TSI0_CH4/PTA3/UART0_RTS_b/FTM0_CH0/JTAG_TMS/SWD_DIO, identifier: D_C4, direction: OUTPUT}
  - {pin_num: '144', peripheral: GPIOD, signal: 'GPIO, 15', pin_signal: PTD15/SPI2_PCS1/SDHC0_D7/FB_A23, identifier: D_SEG_A, direction: OUTPUT}
  - {pin_num: '142', peripheral: GPIOD, signal: 'GPIO, 13', pin_signal: PTD13/SPI2_SOUT/SDHC0_D5/FB_A21, identifier: D_SEG_F, direction: OUTPUT}
  - {pin_num: '141', peripheral: GPIOD, signal: 'GPIO, 12', pin_signal: PTD12/SPI2_SCK/SDHC0_D4/FB_A20, identifier: D_SEG_B, direction: OUTPUT}
  - {pin_num: '143', peripheral: GPIOD, signal: 'GPIO, 14', pin_signal: PTD14/SPI2_SIN/SDHC0_D6/FB_A22, identifier: D_SEG_E, direction: OUTPUT}
  - {pin_num: '47', peripheral: GPIOE, signal: 'GPIO, 26', pin_signal: PTE26/ENET_1588_CLKIN/UART4_CTS_b/RTC_CLKOUT/USB_CLKIN, identifier: FUN_BTN, direction: INPUT,
    gpio_interrupt: kPORT_InterruptFallingEdge}
  - {pin_num: '27', peripheral: ADC0, signal: 'DP, 0', pin_signal: PGA0_DP/ADC0_DP0/ADC1_DP3}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t D_C1_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA2 (pin 52)  */
    GPIO_PinInit(BOARD_INITPINS_D_C1_GPIO, BOARD_INITPINS_D_C1_PIN, &D_C1_config);

    gpio_pin_config_t D_C4_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA3 (pin 53)  */
    GPIO_PinInit(BOARD_INITPINS_D_C4_GPIO, BOARD_INITPINS_D_C4_PIN, &D_C4_config);

    gpio_pin_config_t D_SEG_C_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA6 (pin 58)  */
    GPIO_PinInit(BOARD_INITPINS_D_SEG_C_GPIO, BOARD_INITPINS_D_SEG_C_PIN, &D_SEG_C_config);

    gpio_pin_config_t D_C2_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA7 (pin 59)  */
    GPIO_PinInit(BOARD_INITPINS_D_C2_GPIO, BOARD_INITPINS_D_C2_PIN, &D_C2_config);

    gpio_pin_config_t D_SEG_D_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA8 (pin 60)  */
    GPIO_PinInit(BOARD_INITPINS_D_SEG_D_GPIO, BOARD_INITPINS_D_SEG_D_PIN, &D_SEG_D_config);

    gpio_pin_config_t D_C3_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA9 (pin 61)  */
    GPIO_PinInit(BOARD_INITPINS_D_C3_GPIO, BOARD_INITPINS_D_C3_PIN, &D_C3_config);

    gpio_pin_config_t D_SEG_DOT_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA10 (pin 62)  */
    GPIO_PinInit(BOARD_INITPINS_D_SEG_DOT_GPIO, BOARD_INITPINS_D_SEG_DOT_PIN, &D_SEG_DOT_config);

    gpio_pin_config_t D_SEG_G_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA11 (pin 63)  */
    GPIO_PinInit(BOARD_INITPINS_D_SEG_G_GPIO, BOARD_INITPINS_D_SEG_G_PIN, &D_SEG_G_config);

    gpio_pin_config_t D_SEG_B_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD12 (pin 141)  */
    GPIO_PinInit(BOARD_INITPINS_D_SEG_B_GPIO, BOARD_INITPINS_D_SEG_B_PIN, &D_SEG_B_config);

    gpio_pin_config_t D_SEG_F_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD13 (pin 142)  */
    GPIO_PinInit(BOARD_INITPINS_D_SEG_F_GPIO, BOARD_INITPINS_D_SEG_F_PIN, &D_SEG_F_config);

    gpio_pin_config_t D_SEG_E_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD14 (pin 143)  */
    GPIO_PinInit(BOARD_INITPINS_D_SEG_E_GPIO, BOARD_INITPINS_D_SEG_E_PIN, &D_SEG_E_config);

    gpio_pin_config_t D_SEG_A_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD15 (pin 144)  */
    GPIO_PinInit(BOARD_INITPINS_D_SEG_A_GPIO, BOARD_INITPINS_D_SEG_A_PIN, &D_SEG_A_config);

    gpio_pin_config_t FUN_BTN_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE26 (pin 47)  */
    GPIO_PinInit(BOARD_INITPINS_FUN_BTN_GPIO, BOARD_INITPINS_FUN_BTN_PIN, &FUN_BTN_config);

    /* PORTA10 (pin 62) is configured as PTA10 */
    PORT_SetPinMux(BOARD_INITPINS_D_SEG_DOT_PORT, BOARD_INITPINS_D_SEG_DOT_PIN, kPORT_MuxAsGpio);

    /* PORTA11 (pin 63) is configured as PTA11 */
    PORT_SetPinMux(BOARD_INITPINS_D_SEG_G_PORT, BOARD_INITPINS_D_SEG_G_PIN, kPORT_MuxAsGpio);

    /* PORTA2 (pin 52) is configured as PTA2 */
    PORT_SetPinMux(BOARD_INITPINS_D_C1_PORT, BOARD_INITPINS_D_C1_PIN, kPORT_MuxAsGpio);

    /* PORTA3 (pin 53) is configured as PTA3 */
    PORT_SetPinMux(BOARD_INITPINS_D_C4_PORT, BOARD_INITPINS_D_C4_PIN, kPORT_MuxAsGpio);

    /* PORTA6 (pin 58) is configured as PTA6 */
    PORT_SetPinMux(BOARD_INITPINS_D_SEG_C_PORT, BOARD_INITPINS_D_SEG_C_PIN, kPORT_MuxAsGpio);

    /* PORTA7 (pin 59) is configured as PTA7 */
    PORT_SetPinMux(BOARD_INITPINS_D_C2_PORT, BOARD_INITPINS_D_C2_PIN, kPORT_MuxAsGpio);

    /* PORTA8 (pin 60) is configured as PTA8 */
    PORT_SetPinMux(BOARD_INITPINS_D_SEG_D_PORT, BOARD_INITPINS_D_SEG_D_PIN, kPORT_MuxAsGpio);

    /* PORTA9 (pin 61) is configured as PTA9 */
    PORT_SetPinMux(BOARD_INITPINS_D_C3_PORT, BOARD_INITPINS_D_C3_PIN, kPORT_MuxAsGpio);

    /* PORTD12 (pin 141) is configured as PTD12 */
    PORT_SetPinMux(BOARD_INITPINS_D_SEG_B_PORT, BOARD_INITPINS_D_SEG_B_PIN, kPORT_MuxAsGpio);

    /* PORTD13 (pin 142) is configured as PTD13 */
    PORT_SetPinMux(BOARD_INITPINS_D_SEG_F_PORT, BOARD_INITPINS_D_SEG_F_PIN, kPORT_MuxAsGpio);

    /* PORTD14 (pin 143) is configured as PTD14 */
    PORT_SetPinMux(BOARD_INITPINS_D_SEG_E_PORT, BOARD_INITPINS_D_SEG_E_PIN, kPORT_MuxAsGpio);

    /* PORTD15 (pin 144) is configured as PTD15 */
    PORT_SetPinMux(BOARD_INITPINS_D_SEG_A_PORT, BOARD_INITPINS_D_SEG_A_PIN, kPORT_MuxAsGpio);

    /* PORTE26 (pin 47) is configured as PTE26 */
    PORT_SetPinMux(BOARD_INITPINS_FUN_BTN_PORT, BOARD_INITPINS_FUN_BTN_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTE26 (pin 47): Interrupt on falling edge */
    PORT_SetPinInterruptConfig(BOARD_INITPINS_FUN_BTN_PORT, BOARD_INITPINS_FUN_BTN_PIN, kPORT_InterruptFallingEdge);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
