/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTA6 (number 58), D_SEG_C
  @{ */
#define BOARD_INITPINS_D_SEG_C_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_D_SEG_C_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_D_SEG_C_PIN 6U     /*!<@brief PORTA pin index: 6 */
                                          /* @} */

/*! @name PORTA7 (number 59), D_C2
  @{ */
#define BOARD_INITPINS_D_C2_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_D_C2_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_D_C2_PIN 7U     /*!<@brief PORTA pin index: 7 */
                                       /* @} */

/*! @name PORTA8 (number 60), D_SEG_D
  @{ */
#define BOARD_INITPINS_D_SEG_D_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_D_SEG_D_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_D_SEG_D_PIN 8U     /*!<@brief PORTA pin index: 8 */
                                          /* @} */

/*! @name PORTA9 (number 61), D_C3
  @{ */
#define BOARD_INITPINS_D_C3_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_D_C3_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_D_C3_PIN 9U     /*!<@brief PORTA pin index: 9 */
                                       /* @} */

/*! @name PORTA10 (number 62), D_SEG_DOT
  @{ */
#define BOARD_INITPINS_D_SEG_DOT_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_D_SEG_DOT_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_D_SEG_DOT_PIN 10U    /*!<@brief PORTA pin index: 10 */
                                            /* @} */

/*! @name PORTA11 (number 63), D_SEG_G
  @{ */
#define BOARD_INITPINS_D_SEG_G_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_D_SEG_G_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_D_SEG_G_PIN 11U    /*!<@brief PORTA pin index: 11 */
                                          /* @} */

/*! @name PORTA2 (number 52), D_C1
  @{ */
#define BOARD_INITPINS_D_C1_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_D_C1_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_D_C1_PIN 2U     /*!<@brief PORTA pin index: 2 */
                                       /* @} */

/*! @name PORTA3 (number 53), D_C4
  @{ */
#define BOARD_INITPINS_D_C4_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_D_C4_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_D_C4_PIN 3U     /*!<@brief PORTA pin index: 3 */
                                       /* @} */

/*! @name PORTD15 (number 144), D_SEG_A
  @{ */
#define BOARD_INITPINS_D_SEG_A_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_D_SEG_A_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_D_SEG_A_PIN 15U    /*!<@brief PORTD pin index: 15 */
                                          /* @} */

/*! @name PORTD13 (number 142), D_SEG_F
  @{ */
#define BOARD_INITPINS_D_SEG_F_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_D_SEG_F_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_D_SEG_F_PIN 13U    /*!<@brief PORTD pin index: 13 */
                                          /* @} */

/*! @name PORTD12 (number 141), D_SEG_B
  @{ */
#define BOARD_INITPINS_D_SEG_B_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_D_SEG_B_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_D_SEG_B_PIN 12U    /*!<@brief PORTD pin index: 12 */
                                          /* @} */

/*! @name PORTD14 (number 143), D_SEG_E
  @{ */
#define BOARD_INITPINS_D_SEG_E_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_D_SEG_E_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_D_SEG_E_PIN 14U    /*!<@brief PORTD pin index: 14 */
                                          /* @} */

/*! @name PORTE26 (number 47), FUN_BTN
  @{ */
#define BOARD_INITPINS_FUN_BTN_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_FUN_BTN_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_FUN_BTN_PIN 26U    /*!<@brief PORTE pin index: 26 */
                                          /* @} */

/*! @name ADC0_DP0 (number 27), SENSOR
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
